### ISSUE TITLE
How do I download the rewritten binary to target?

### ISSUE THREAD

**Issue by shijiameng** [pwnforce/uSBS#6]
Hello,

I was trying to rewrite the binary with uSBS. I encountered some problems:

1. Based on the paper, the firmware entry point would be redirected to `.newsec` (`.newtext`) section (Am I correct?) Does this mean it's enough to download `.newtext` section to the target device? Do I still need to dowoload the original binary to the flash memory as well? In the former case, if download the `.newtext` section to my Nucleo-F401RE board, it traps into hard fault. In the latter case, it runs the original firmware, other than the rewritten one

2. I rewrote the firmware using the command line provided in the readme, it seems that it only translated the binary but didn't instrument ASan. How do I enable ASan instrumentation? 

Thanks.

**Comment by pwnforce** [comment]
uSBS adds a new code section called .newtext along original code section. Thus, you need to have both of them in your device. Also, you need to adjust the entry point manually by yourself (pointing to the .newtext entry point). 
As for the second question, please check asan.py and tune the instrumentation for your specific firmware.

**Comment by shijiameng** [comment]
Thank you for your reply. I need to redirect the entries in the vector table to the offset in .newtext section, am I correct?

**Comment by pwnforce** [comment]
Yes, that is true. You can do it with a simple hex editor.
