### ISSUE TITLE
Can you give the original code you did in your experiment?

### ISSUE THREAD

**Issue by wsxk** [pwnforce/uSBS#8]
It seems that the code in github is not complete. usbs.py doesn't use the maptext and the asan policy,I don't know how to revise it. 
Could you please provide some examples or documentation?

**Comment by pwnforce** [comment]
The code is complete and tested with the devices mentioned in the ReadMe file. Indeed, asan.py uses usbs.py. Instrumentations are defined in asan.py and passed to the usbs.py to be inserted.

**Comment by wsxk** [comment]
I mean，i know the code can be tested with the devices in the ReadMe file. Actually I check the firmware instrumentated by your tool with IDA pro. It seems that your code doesn't actually instrument the firmware

**Comment by pwnforce** [comment]
You cannot see the instrumented code in IDA pro since it is stripped. I think the code that you are seeing is the original code section which is not instrumented. Instead, you need to check the new code section in a hex reader.

**Comment by wsxk** [comment]
Thanks for your reply! I'll check it again
